### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by KjellKod** [moswald/xunitpp#1]
Hi, 

I found this through a comment of yours on stackoverflow. I like the idea of a good featured and small testing library. 
Have you considered adding usage documentation to this? or can you link to usage documentation if you put it elsewhere?

**Comment by moswald** [comment]
Wow. I completely forgot about this project. I haven't written any C++ code in quite some time. 😆

I'm afraid you can consider this project to be abandoned. I don't plan to add any features or documentation, but it worked well (a whole decade ago) and if you check out the `Tests/UnitTests` folder you can see how xunitpp tests itself.

That said, I will look around for some documentation. I know I had written something at some point, but I'm afraid it might have been on my long-gone BitBucket account.

**Comment by KjellKod** [comment]
I figured as much and moved on with gtest.

Regardless, the code looked promising. Just a big deterrent without some
markdown examples for a quick overview
